#!/usr/bin/env python

import os
import sys
import time
import requests as r


url = sys.argv[1]
user_agent = 'annoy/0.1'


def request(url):
	response = r.get(url = url)
	return response.status_code

def retry(url, delay, status):
	status_code = request(url)
	print "Status code: " + str(status_code)
	while status_code != status:
		time.sleep(delay)
		print "Retrying..."
		status_code = request(url)
		continue
	print "It's available!"

retry(url, 30, 200)
